version: 0.2

env:
  variables:
    SONAR_LOGIN: "MY_SONARQUBE_AUTHTOKEN"
    SONAR_HOST: "MY_SONARQUBE_URL"
    #You should use parameter-store here instead

phases:
  build:
    commands:
      - mvn test
  post_build:
    commands:
      - mvn sonar:sonar -Dsonar.host.url=http://ec2-54-210-143-14.compute-1.amazonaws.com  -Dsonar.login=a87635e32e84d1e9613b5cb0602c40ecb7f02f4a
